// <auto-generated />
using System;
using DotnetTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512104550_FruitAndVegetableCatalog")]
    partial class FruitAndVegetableCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DotnetTest.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "FreshMart merkez ofis",
                            Email = "admin@freshmart.com",
                            FullName = "Admin User",
                            Password = "123",
                            Phone = "0555 000 00 01",
                            Role = "Admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Örnek mahalle, örnek sokak",
                            Email = "user@freshmart.com",
                            FullName = "Normal User",
                            Password = "123",
                            Phone = "0555 000 00 02",
                            Role = "User",
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("DotnetTest.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("DotnetTest.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Meyve"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sebze"
                        });
                });

            modelBuilder.Entity("DotnetTest.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryFullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DotnetTest.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DotnetTest.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Tatlı ve sulu kırmızı elma.",
                            ImageUrl = "",
                            Name = "Kırmızı Elma",
                            Price = 34.90m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Günlük taze domates.",
                            ImageUrl = "",
                            Name = "Domates",
                            Price = 28.50m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Olgun ve lezzetli muz.",
                            ImageUrl = "",
                            Name = "Muz",
                            Price = 49.90m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Çıtır ve taze salatalık.",
                            ImageUrl = "",
                            Name = "Salatalık",
                            Price = 22.90m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Bol sulu portakal.",
                            ImageUrl = "",
                            Name = "Portakal",
                            Price = 32.90m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Kokulu taze çilek.",
                            ImageUrl = "",
                            Name = "Çilek",
                            Price = 69.90m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Yumuşak ve tatlı armut.",
                            ImageUrl = "",
                            Name = "Armut",
                            Price = 38.90m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Tatlı sofralık üzüm.",
                            ImageUrl = "",
                            Name = "Üzüm",
                            Price = 44.90m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Ekşi tatlı taze kivi.",
                            ImageUrl = "",
                            Name = "Kivi",
                            Price = 59.90m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Sulu yaz şeftalisi.",
                            ImageUrl = "",
                            Name = "Şeftali",
                            Price = 42.90m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Tatlı ve serin karpuz.",
                            ImageUrl = "",
                            Name = "Karpuz",
                            Price = 14.90m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Bol sulu limon.",
                            ImageUrl = "",
                            Name = "Limon",
                            Price = 24.90m,
                            Stock = 65
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Yemeklik taze patates.",
                            ImageUrl = "",
                            Name = "Patates",
                            Price = 19.90m,
                            Stock = 110
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Kuru yemeklik soğan.",
                            ImageUrl = "",
                            Name = "Soğan",
                            Price = 17.90m,
                            Stock = 95
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Taze yeşil biber.",
                            ImageUrl = "",
                            Name = "Biber",
                            Price = 36.90m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Çıtır taze havuç.",
                            ImageUrl = "",
                            Name = "Havuç",
                            Price = 21.90m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Canlı ve taze marul.",
                            ImageUrl = "",
                            Name = "Marul",
                            Price = 18.90m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Taze brokoli.",
                            ImageUrl = "",
                            Name = "Brokoli",
                            Price = 39.90m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Yemeklik taze kabak.",
                            ImageUrl = "",
                            Name = "Kabak",
                            Price = 26.90m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Parlak ve taze patlıcan.",
                            ImageUrl = "",
                            Name = "Patlıcan",
                            Price = 29.90m,
                            Stock = 50
                        });
                });

            modelBuilder.Entity("DotnetTest.Models.CartItem", b =>
                {
                    b.HasOne("DotnetTest.Models.AppUser", "AppUser")
                        .WithMany("CartItems")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotnetTest.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DotnetTest.Models.Order", b =>
                {
                    b.HasOne("DotnetTest.Models.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("DotnetTest.Models.OrderItem", b =>
                {
                    b.HasOne("DotnetTest.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotnetTest.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DotnetTest.Models.Product", b =>
                {
                    b.HasOne("DotnetTest.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DotnetTest.Models.AppUser", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DotnetTest.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DotnetTest.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
